package router

import (
	_ "gin_example/docs/swagger" // docs is generated by Swag CLI, you have to import it.

	commonMiddleware "gin_example/common/middleware"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

func NewRouter() *gin.Engine {
	r := gin.Default()
	r.Use(commonMiddleware.Translations())
	r.Use(commonMiddleware.ErrHandler())
	// r.Use(commonMiddleware.AccessLog())

	RoleRouter(r)

	// http://xxx/swagger/index.html
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	return r
}
